export interface ExchangeConfig {
	key: string;
	name: string;
	shortLabel: string;
	historyEnabled: boolean;
	hasRwaAssets?: boolean;
	benefits?: string;
	logoFilename: string;
	referralUrl: string;
}

export const EXCHANGES: ExchangeConfig[] = [
	{
		key: "hyperliquid",
		name: "HyperLiquid",
		shortLabel: "HL",
		historyEnabled: true,
		hasRwaAssets: true,
		benefits: "-5% fees",
		logoFilename: "hyperliquid.svg",
		referralUrl: "https://app.hyperliquid.xyz/join/NAVIX",
	},
	{
		key: "lighter",
		name: "Lighter",
		shortLabel: "LGT",
		historyEnabled: true,
		hasRwaAssets: true,
		logoFilename: "lighter.png",
		referralUrl: "https://app.lighter.xyz/trade",
	},
	{
		key: "extended",
		name: "Extended",
		shortLabel: "EXT",
		historyEnabled: true,
		hasRwaAssets: true,
		benefits: "-10% fees",
		logoFilename: "extended.png",
		referralUrl: "https://app.extended.exchange/join/NAVIX",
	},
	{
		key: "paradex",
		name: "Paradex",
		shortLabel: "PDX",
		historyEnabled: true,
		benefits: "5% XP boost",
		logoFilename: "paradex.svg",
		referralUrl: "https://app.paradex.trade/r/navix",
	},
	{
		key: "edgex",
		name: "EdgeX",
		shortLabel: "EDGX",
		historyEnabled: true,
		logoFilename: "edgex.svg",
		referralUrl: "https://pro.edgex.exchange/referral/TOOMANYCOOKS",
	},
	{
		key: "asterdex",
		name: "Aster",
		shortLabel: "AST",
		historyEnabled: true,
		hasRwaAssets: true,
		benefits: "-5% fees",
		logoFilename: "aster.png",
		referralUrl: "https://asterdex.com/en/referral/eQUFa6",
	},
	{
		key: "variational",
		name: "Variational",
		shortLabel: "VAR",
		historyEnabled: true,
		benefits: "Get private access",
		logoFilename: "variational.png",
		referralUrl: "https://omni.variational.io/?ref=OMNIJK8T965Z",
	},
	{
		key: "reya",
		name: "Reya",
		shortLabel: "REYA",
		historyEnabled: true,
		benefits: "-10% fees",
		logoFilename: "reya.png",
		referralUrl: "https://app.reya.xyz/?referredBy=eravs97y",
	},
	{
		key: "pacifica",
		name: "Pacifica",
		shortLabel: "PCF",
		historyEnabled: true,
		logoFilename: "pacifica.png",
		referralUrl: "https://pacifica.fi",
	},
	{
		key: "backpack",
		name: "Backpack",
		shortLabel: "BKPK",
		historyEnabled: true,
		logoFilename: "backpack.png",
		referralUrl: "https://backpack.exchange/join/44337eb6-426c-4cb4-8a32-929b5051ab96",
	},
	{
		key: "ethereal",
		name: "Ethereal",
		shortLabel: "ETHRL",
		historyEnabled: true,
		logoFilename: "ethereal.svg",
		referralUrl: "https://ethereal.trade",
	},
	{
		key: "vest",
		name: "Vest",
		shortLabel: "VEST",
		historyEnabled: true,
		hasRwaAssets: true,
		benefits: "No fees",
		logoFilename: "vest.png",
		referralUrl: "https://trade.vest.exchange/join/NAVIX",
	},
	{
		key: "tradexyz",
		name: "TradeXYZ",
		shortLabel: "XYZ",
		historyEnabled: true,
		hasRwaAssets: true,
		logoFilename: "tradexyz.png",
		referralUrl: "https://app.tradexyz.com/",
	},
	{
		key: "drift",
		name: "Drift",
		shortLabel: "DRFT",
		historyEnabled: true,
		logoFilename: "drift.png",
		referralUrl: "https://app.drift.trade/ref/navix",
	},
	{
		key: "evedex",
		name: "Evedex",
		shortLabel: "EVDX",
		historyEnabled: true,
		logoFilename: "evedex.png",
		referralUrl: "https://invite.evedex.com/vt72lp6p",
	},
	{
		key: "apex",
		name: "APEX",
		shortLabel: "APEX",
		historyEnabled: true,
		benefits: "-5% to -10% fees",
		logoFilename: "apex.png",
		referralUrl: "https://omni.apex.exchange/referral?code=SF8S961L",
	},
	{
		key: "arkm",
		name: "ARKM",
		shortLabel: "ARKM",
		historyEnabled: true,
		logoFilename: "arkm.png",
		referralUrl: "https://arkm.com/markets/perpetuals",
	},
	{
		key: "dydx",
		name: "dYdX",
		shortLabel: "DYDX",
		historyEnabled: true,
		logoFilename: "dydx.png",
		referralUrl: "https://dydx.trade?ref=TensePeaceFS5",
	},
	{
		key: "aevo",
		name: "Aevo",
		shortLabel: "AEVO",
		historyEnabled: true,
		logoFilename: "aevo.png",
		referralUrl: "https://app.aevo.xyz/r/Sable-Beautiful-Cronje",
	},
	{
		key: "01",
		name: "01",
		shortLabel: "01",
		historyEnabled: true,
		logoFilename: "01.png",
		referralUrl: "https://01.xyz/",
	},
	{
		key: "nado",
		name: "Nado",
		shortLabel: "NADO",
		historyEnabled: true,
		logoFilename: "nado.webp",
		referralUrl: "https://app.nado.xyz?join=wJZM6PU",
	},
	{
		key: "grvt",
		name: "GRVT",
		shortLabel: "GRVT",
		historyEnabled: true,
		logoFilename: "grvt.webp",
		referralUrl: "https://grvt.io/?ref=K3MDUJ7",
	},
	{
		key: "astros",
		name: "Astros",
		shortLabel: "ASTR",
		historyEnabled: true,
		logoFilename: "astros.png",
		referralUrl: "https://astros.ag/perp/SUI-USD?referralCode=EFYROR",
	},
	{
		key: "standx",
		name: "StandX",
		shortLabel: "STDX",
		historyEnabled: true,
		logoFilename: "standx.png",
		referralUrl: "https://standx.com/referral?code=Toomanycooks",
	},
	{
		key: "hibachi",
		name: "Hibachi",
		shortLabel: "HIB",
		historyEnabled: true,
		logoFilename: "hibachi.webp",
		referralUrl: "https://hibachi.xyz/r/2SYPWDVJUE",
	},
	{
		key: "bullpen",
		name: "Bullpen",
		shortLabel: "BUL",
		historyEnabled: true,
		hasRwaAssets: true,
		logoFilename: "bullpen.webp",
		referralUrl: "https://bullpen.fi/@toomanycooks",
	},
];
